### ISSUE TITLE
PWN 3.0 and 3.1 data

### ISSUE THREAD

**Issue by arademaker** [omwn/omw-data#29]
1. https://github.com/omwn/omw-data/tree/main/wns/en30
2. https://github.com/omwn/omw-data/tree/main/wns/en31

In these folders, I didn't find the proper data files. Where are they?

**Comment by goodmami** [comment]
The Princeton WordNet data is not distributed by OMW, but it is used in creating the `omw-en` and `omw-en31` lexicons. You can see in the `build.sh` script that it is downloaded when building the lexicons:

https://github.com/omwn/omw-data/blob/3881c90104878147fd2b0bc1b50ff6ece4550ca4/build.sh#L40-L51

https://github.com/omwn/omw-data/blob/3881c90104878147fd2b0bc1b50ff6ece4550ca4/build.sh#L72-L80
